-- ============================================================
-- Województwa (regions) + powiaty (counties). regions = województwa.
-- ============================================================

-- Tabela powiatów (powiat należy do województwa)
CREATE TABLE IF NOT EXISTS public.counties (
  id         SERIAL PRIMARY KEY,
  region_id  INT NOT NULL REFERENCES public.regions(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  UNIQUE(region_id, name)
);

CREATE INDEX IF NOT EXISTS idx_counties_region ON public.counties(region_id);

-- Listings: dodanie powiatu
ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS county_id INT REFERENCES public.counties(id);

CREATE INDEX IF NOT EXISTS idx_listings_county ON public.listings(county_id);

-- Profiles: powiat + miasto (opcjonalne)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS county_id INT REFERENCES public.counties(id);
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS city TEXT;

-- RLS: powiaty – odczyt dla wszystkich
ALTER TABLE public.counties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "counties_select_all" ON public.counties FOR SELECT USING (true);

-- Seed: 16 województw (jeśli tabela regions jest pusta lub brakuje nazw)
INSERT INTO public.regions (name) VALUES
  ('dolnośląskie'),
  ('kujawsko-pomorskie'),
  ('lubelskie'),
  ('lubuskie'),
  ('łódzkie'),
  ('małopolskie'),
  ('mazowieckie'),
  ('opolskie'),
  ('podkarpackie'),
  ('podlaskie'),
  ('pomorskie'),
  ('śląskie'),
  ('świętokrzyskie'),
  ('warmińsko-mazurskie'),
  ('wielkopolskie'),
  ('zachodniopomorskie')
ON CONFLICT (name) DO NOTHING;

-- Seed: powiaty (380 – lista z TERYT/Wikipedia)
INSERT INTO public.counties (region_id, name)
SELECT r.id, c.county_name FROM public.regions r
JOIN (VALUES
  ('kujawsko-pomorskie','aleksandrowski'),
  ('podlaskie','augustowski'),
  ('warmińsko-mazurskie','bartoszycki'),
  ('łódzkie','bełchatowski'),
  ('śląskie','będziński'),
  ('lubelskie','bialski'),
  ('lubelskie','Biała Podlaska'),
  ('mazowieckie','białobrzeski'),
  ('zachodniopomorskie','białogardzki'),
  ('podlaskie','białostocki'),
  ('podlaskie','Białystok'),
  ('śląskie','bielski'),
  ('podlaskie','bielski'),
  ('śląskie','Bielsko-Biała'),
  ('śląskie','bieruńsko-lędziński'),
  ('podkarpackie','bieszczadzki'),
  ('lubelskie','biłgorajski'),
  ('małopolskie','bocheński'),
  ('dolnośląskie','bolesławiecki'),
  ('warmińsko-mazurskie','braniewski'),
  ('kujawsko-pomorskie','brodnicki'),
  ('małopolskie','brzeski'),
  ('opolskie','brzeski'),
  ('łódzkie','brzeziński'),
  ('podkarpackie','brzozowski'),
  ('świętokrzyskie','buski'),
  ('kujawsko-pomorskie','bydgoski'),
  ('kujawsko-pomorskie','Bydgoszcz'),
  ('śląskie','Bytom'),
  ('pomorskie','bytowski'),
  ('lubelskie','Chełm'),
  ('kujawsko-pomorskie','chełmiński'),
  ('lubelskie','chełmski'),
  ('wielkopolskie','chodzieski'),
  ('pomorskie','chojnicki'),
  ('śląskie','Chorzów'),
  ('zachodniopomorskie','choszczeński'),
  ('małopolskie','chrzanowski'),
  ('mazowieckie','ciechanowski'),
  ('śląskie','cieszyński'),
  ('wielkopolskie','czarnkowsko-trzcianecki'),
  ('śląskie','Częstochowa'),
  ('śląskie','częstochowski'),
  ('pomorskie','człuchowski'),
  ('śląskie','Dąbrowa Górnicza'),
  ('małopolskie','dąbrowski'),
  ('podkarpackie','dębicki'),
  ('zachodniopomorskie','drawski'),
  ('warmińsko-mazurskie','działdowski'),
  ('dolnośląskie','dzierżoniowski'),
  ('warmińsko-mazurskie','Elbląg'),
  ('warmińsko-mazurskie','elbląski'),
  ('warmińsko-mazurskie','ełcki'),
  ('mazowieckie','garwoliński'),
  ('pomorskie','Gdańsk'),
  ('pomorskie','gdański'),
  ('pomorskie','Gdynia'),
  ('warmińsko-mazurskie','giżycki'),
  ('śląskie','Gliwice'),
  ('śląskie','gliwicki'),
  ('dolnośląskie','głogowski'),
  ('opolskie','głubczycki'),
  ('wielkopolskie','gnieźnieński'),
  ('zachodniopomorskie','goleniowski'),
  ('kujawsko-pomorskie','golubsko-dobrzyński'),
  ('warmińsko-mazurskie','gołdapski'),
  ('małopolskie','gorlicki'),
  ('lubuskie','gorzowski'),
  ('lubuskie','Gorzów Wielkopolski'),
  ('mazowieckie','gostyniński'),
  ('wielkopolskie','gostyński'),
  ('dolnośląskie','górowski'),
  ('podlaskie','grajewski'),
  ('mazowieckie','grodziski'),
  ('wielkopolskie','grodziski'),
  ('mazowieckie','grójecki'),
  ('kujawsko-pomorskie','Grudziądz'),
  ('kujawsko-pomorskie','grudziądzki'),
  ('zachodniopomorskie','gryficki'),
  ('zachodniopomorskie','gryfiński'),
  ('podlaskie','hajnowski'),
  ('lubelskie','hrubieszowski'),
  ('warmińsko-mazurskie','iławski'),
  ('kujawsko-pomorskie','inowrocławski'),
  ('lubelskie','janowski'),
  ('wielkopolskie','jarociński'),
  ('podkarpackie','jarosławski'),
  ('podkarpackie','jasielski'),
  ('śląskie','Jastrzębie-Zdrój'),
  ('dolnośląskie','jaworski'),
  ('śląskie','Jaworzno'),
  ('dolnośląskie','Jelenia Góra'),
  ('świętokrzyskie','jędrzejowski'),
  ('wielkopolskie','kaliski'),
  ('wielkopolskie','Kalisz'),
  ('dolnośląskie','kamiennogórski'),
  ('zachodniopomorskie','kamieński'),
  ('dolnośląskie','karkonoski'),
  ('pomorskie','kartuski'),
  ('śląskie','Katowice'),
  ('świętokrzyskie','kazimierski'),
  ('opolskie','kędzierzyńsko-kozielski'),
  ('wielkopolskie','kępiński'),
  ('warmińsko-mazurskie','kętrzyński'),
  ('świętokrzyskie','Kielce'),
  ('świętokrzyskie','kielecki'),
  ('opolskie','kluczborski'),
  ('śląskie','kłobucki'),
  ('dolnośląskie','kłodzki'),
  ('podkarpackie','kolbuszowski'),
  ('podlaskie','kolneński'),
  ('wielkopolskie','kolski'),
  ('zachodniopomorskie','kołobrzeski'),
  ('świętokrzyskie','konecki'),
  ('wielkopolskie','Konin'),
  ('wielkopolskie','koniński'),
  ('zachodniopomorskie','Koszalin'),
  ('zachodniopomorskie','koszaliński'),
  ('wielkopolskie','kościański'),
  ('pomorskie','kościerski'),
  ('mazowieckie','kozienicki'),
  ('małopolskie','krakowski'),
  ('małopolskie','Kraków'),
  ('opolskie','krapkowicki'),
  ('lubelskie','krasnostawski'),
  ('lubelskie','kraśnicki'),
  ('podkarpackie','Krosno'),
  ('podkarpackie','krośnieński'),
  ('lubuskie','krośnieński'),
  ('wielkopolskie','krotoszyński'),
  ('łódzkie','kutnowski'),
  ('pomorskie','kwidzyński'),
  ('mazowieckie','legionowski'),
  ('dolnośląskie','Legnica'),
  ('dolnośląskie','legnicki'),
  ('podkarpackie','leski'),
  ('wielkopolskie','leszczyński'),
  ('wielkopolskie','Leszno'),
  ('podkarpackie','leżajski'),
  ('pomorskie','lęborski'),
  ('warmińsko-mazurskie','lidzbarski'),
  ('małopolskie','limanowski'),
  ('kujawsko-pomorskie','lipnowski'),
  ('mazowieckie','lipski'),
  ('podkarpackie','lubaczowski'),
  ('dolnośląskie','lubański'),
  ('lubelskie','lubartowski'),
  ('lubelskie','lubelski'),
  ('dolnośląskie','lubiński'),
  ('lubelskie','Lublin'),
  ('śląskie','lubliniecki'),
  ('dolnośląskie','lwówecki'),
  ('podkarpackie','łańcucki'),
  ('łódzkie','łaski'),
  ('łódzkie','łęczycki'),
  ('lubelskie','łęczyński'),
  ('zachodniopomorskie','łobeski'),
  ('podlaskie','Łomża'),
  ('podlaskie','łomżyński'),
  ('mazowieckie','łosicki'),
  ('łódzkie','łowicki'),
  ('łódzkie','łódzki wschodni'),
  ('łódzkie','Łódź'),
  ('lubelskie','łukowski'),
  ('mazowieckie','makowski'),
  ('pomorskie','malborski'),
  ('małopolskie','miechowski'),
  ('podkarpackie','mielecki'),
  ('wielkopolskie','międzychodzki'),
  ('lubuskie','międzyrzecki'),
  ('śląskie','mikołowski'),
  ('dolnośląskie','milicki'),
  ('mazowieckie','miński'),
  ('mazowieckie','mławski'),
  ('kujawsko-pomorskie','mogileński'),
  ('podlaskie','moniecki'),
  ('warmińsko-mazurskie','mrągowski'),
  ('śląskie','Mysłowice'),
  ('śląskie','myszkowski'),
  ('małopolskie','myślenicki'),
  ('zachodniopomorskie','myśliborski'),
  ('kujawsko-pomorskie','nakielski'),
  ('opolskie','namysłowski'),
  ('warmińsko-mazurskie','nidzicki'),
  ('podkarpackie','niżański'),
  ('pomorskie','nowodworski'),
  ('mazowieckie','nowodworski'),
  ('warmińsko-mazurskie','nowomiejski'),
  ('małopolskie','nowosądecki'),
  ('lubuskie','nowosolski'),
  ('małopolskie','nowotarski'),
  ('wielkopolskie','nowotomyski'),
  ('małopolskie','Nowy Sącz'),
  ('opolskie','nyski'),
  ('wielkopolskie','obornicki'),
  ('warmińsko-mazurskie','olecki'),
  ('opolskie','oleski'),
  ('dolnośląskie','oleśnicki'),
  ('małopolskie','olkuski'),
  ('warmińsko-mazurskie','Olsztyn'),
  ('warmińsko-mazurskie','olsztyński'),
  ('dolnośląskie','oławski'),
  ('świętokrzyskie','opatowski'),
  ('łódzkie','opoczyński'),
  ('opolskie','Opole'),
  ('lubelskie','opolski'),
  ('opolskie','opolski'),
  ('mazowieckie','ostrołęcki'),
  ('mazowieckie','Ostrołęka'),
  ('świętokrzyskie','ostrowiecki'),
  ('wielkopolskie','ostrowski'),
  ('mazowieckie','ostrowski'),
  ('warmińsko-mazurskie','ostródzki'),
  ('wielkopolskie','ostrzeszowski'),
  ('małopolskie','oświęcimski'),
  ('mazowieckie','otwocki'),
  ('łódzkie','pabianicki'),
  ('łódzkie','pajęczański'),
  ('lubelskie','parczewski'),
  ('mazowieckie','piaseczyński'),
  ('śląskie','Piekary Śląskie'),
  ('wielkopolskie','pilski'),
  ('świętokrzyskie','pińczowski'),
  ('łódzkie','piotrkowski'),
  ('łódzkie','Piotrków Trybunalski'),
  ('warmińsko-mazurskie','piski'),
  ('wielkopolskie','pleszewski'),
  ('mazowieckie','Płock'),
  ('mazowieckie','płocki'),
  ('mazowieckie','płoński'),
  ('łódzkie','poddębicki'),
  ('zachodniopomorskie','policki'),
  ('dolnośląskie','polkowicki'),
  ('wielkopolskie','Poznań'),
  ('wielkopolskie','poznański'),
  ('małopolskie','proszowicki'),
  ('opolskie','prudnicki'),
  ('mazowieckie','pruszkowski'),
  ('mazowieckie','przasnyski'),
  ('podkarpackie','przemyski'),
  ('podkarpackie','Przemyśl'),
  ('podkarpackie','przeworski'),
  ('mazowieckie','przysuski'),
  ('śląskie','pszczyński'),
  ('pomorskie','pucki'),
  ('lubelskie','puławski'),
  ('mazowieckie','pułtuski'),
  ('zachodniopomorskie','pyrzycki'),
  ('śląskie','raciborski'),
  ('mazowieckie','Radom'),
  ('mazowieckie','radomski'),
  ('łódzkie','radomszczański'),
  ('kujawsko-pomorskie','radziejowski'),
  ('lubelskie','radzyński'),
  ('wielkopolskie','rawicki'),
  ('łódzkie','rawski'),
  ('podkarpackie','ropczycko-sędziszowski'),
  ('śląskie','Ruda Śląska'),
  ('śląskie','rybnicki'),
  ('śląskie','Rybnik'),
  ('lubelskie','rycki'),
  ('kujawsko-pomorskie','rypiński'),
  ('podkarpackie','rzeszowski'),
  ('podkarpackie','Rzeszów'),
  ('świętokrzyskie','sandomierski'),
  ('podkarpackie','sanocki'),
  ('podlaskie','sejneński'),
  ('kujawsko-pomorskie','sępoleński'),
  ('mazowieckie','Siedlce'),
  ('mazowieckie','siedlecki'),
  ('śląskie','Siemianowice Śląskie'),
  ('podlaskie','siemiatycki'),
  ('łódzkie','sieradzki'),
  ('mazowieckie','sierpecki'),
  ('świętokrzyskie','skarżyski'),
  ('łódzkie','Skierniewice'),
  ('łódzkie','skierniewicki'),
  ('zachodniopomorskie','sławieński'),
  ('lubuskie','słubicki'),
  ('wielkopolskie','słupecki'),
  ('pomorskie','Słupsk'),
  ('pomorskie','słupski'),
  ('mazowieckie','sochaczewski'),
  ('mazowieckie','sokołowski'),
  ('podlaskie','sokólski'),
  ('pomorskie','Sopot'),
  ('śląskie','Sosnowiec'),
  ('podkarpackie','stalowowolski'),
  ('świętokrzyskie','starachowicki'),
  ('zachodniopomorskie','stargardzki'),
  ('pomorskie','starogardzki'),
  ('świętokrzyskie','staszowski'),
  ('opolskie','strzelecki'),
  ('lubuskie','strzelecko-drezdenecki'),
  ('dolnośląskie','strzeliński'),
  ('podkarpackie','strzyżowski'),
  ('lubuskie','sulęciński'),
  ('małopolskie','suski'),
  ('podlaskie','suwalski'),
  ('podlaskie','Suwałki'),
  ('wielkopolskie','szamotulski'),
  ('zachodniopomorskie','Szczecin'),
  ('zachodniopomorskie','szczecinecki'),
  ('warmińsko-mazurskie','szczycieński'),
  ('pomorskie','sztumski'),
  ('mazowieckie','szydłowiecki'),
  ('wielkopolskie','średzki'),
  ('dolnośląskie','średzki'),
  ('wielkopolskie','śremski'),
  ('lubelskie','świdnicki'),
  ('dolnośląskie','świdnicki'),
  ('zachodniopomorskie','świdwiński'),
  ('lubuskie','świebodziński'),
  ('kujawsko-pomorskie','świecki'),
  ('śląskie','Świętochłowice'),
  ('zachodniopomorskie','Świnoujście'),
  ('podkarpackie','Tarnobrzeg'),
  ('podkarpackie','tarnobrzeski'),
  ('śląskie','tarnogórski'),
  ('małopolskie','tarnowski'),
  ('małopolskie','Tarnów'),
  ('małopolskie','tatrzański'),
  ('pomorskie','tczewski'),
  ('łódzkie','tomaszowski'),
  ('lubelskie','tomaszowski'),
  ('kujawsko-pomorskie','Toruń'),
  ('kujawsko-pomorskie','toruński'),
  ('dolnośląskie','trzebnicki'),
  ('kujawsko-pomorskie','tucholski'),
  ('wielkopolskie','turecki'),
  ('śląskie','Tychy'),
  ('małopolskie','wadowicki'),
  ('dolnośląskie','Wałbrzych'),
  ('dolnośląskie','wałbrzyski'),
  ('zachodniopomorskie','wałecki'),
  ('mazowieckie','Warszawa'),
  ('mazowieckie','warszawski zachodni'),
  ('kujawsko-pomorskie','wąbrzeski'),
  ('wielkopolskie','wągrowiecki'),
  ('pomorskie','wejherowski'),
  ('warmińsko-mazurskie','węgorzewski'),
  ('mazowieckie','węgrowski'),
  ('małopolskie','wielicki'),
  ('łódzkie','wieluński'),
  ('łódzkie','wieruszowski'),
  ('kujawsko-pomorskie','Włocławek'),
  ('kujawsko-pomorskie','włocławski'),
  ('lubelskie','włodawski'),
  ('świętokrzyskie','włoszczowski'),
  ('śląskie','wodzisławski'),
  ('wielkopolskie','wolsztyński'),
  ('mazowieckie','wołomiński'),
  ('dolnośląskie','wołowski'),
  ('dolnośląskie','Wrocław'),
  ('dolnośląskie','wrocławski'),
  ('wielkopolskie','wrzesiński'),
  ('lubuskie','wschowski'),
  ('podlaskie','wysokomazowiecki'),
  ('mazowieckie','wyszkowski'),
  ('śląskie','Zabrze'),
  ('podlaskie','zambrowski'),
  ('lubelskie','zamojski'),
  ('lubelskie','Zamość'),
  ('śląskie','zawierciański'),
  ('dolnośląskie','ząbkowicki'),
  ('łódzkie','zduńskowolski'),
  ('łódzkie','zgierski'),
  ('dolnośląskie','zgorzelecki'),
  ('lubuskie','Zielona Góra'),
  ('lubuskie','zielonogórski'),
  ('dolnośląskie','złotoryjski'),
  ('wielkopolskie','złotowski'),
  ('mazowieckie','zwoleński'),
  ('lubuskie','żagański'),
  ('lubuskie','żarski'),
  ('kujawsko-pomorskie','żniński'),
  ('śląskie','Żory'),
  ('mazowieckie','żuromiński'),
  ('mazowieckie','żyrardowski'),
  ('śląskie','żywiecki')
) AS c(region_name, county_name) ON r.name = c.region_name
ON CONFLICT (region_id, name) DO NOTHING;
